# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Homepage
    url: /
    weight: 10
  - name: Topics
    url: tags/
    weight: 20
  - name: Research Experience
    url: uses/
    weight: 30
